version: '3.7'


networks:
   churn-network:
       name: churn-network
       driver: bridge
       external: false

services:
   api-ai-churn:
       container_name: api-ai-churn
       image: churn:v1.0.0
       ports:
           - 8080:80
       networks:
          - churn-network
   streamlit-app:
       container_name: streamlit-app
       image: streamlit:v1.0.0
       ports:
           - '8501:8501'
       networks:
           - churn-network